name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: 'New Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: 'Other Changes'
    labels:
      - '*'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'fix'
      - 'bugfix'
      - 'docs'
  default: patch

autolabeler:
  # Match branch naming conventions
  - label: 'feature'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
    title:
      - '/^feat(\(.+\))?:/'
  - label: 'fix'
    branch:
      - '/fix\/.+/'
      - '/bugfix\/.+/'
    title:
      - '/^fix(\(.+\))?:/'
  - label: 'docs'
    branch:
      - '/docs\/.+/'
    title:
      - '/^docs(\(.+\))?:/'
